### ISSUE TITLE
Syntax highlighting: regexes vs division

### ISSUE THREAD

**Issue by zenazn** [rodjek/vim-puppet#46] opened 2014-08-20 23:16 UTC
The syntax highlighting for division isn't correct, as the "/" is interpreted as the beginning of the region for a regex. This is especially nasty because it causes cascading hilarity as the remainder of the file is interpreted as a regular expression.

One simple (but not particularly correct) workaround is to make the `syn region puppetRegex` be a `oneline` rule. This exposes a few other edge cases (if there are two division signs in a single line, for instance, or for a multiline regex if those even exist), but it has the twin benefits of being very easy to implement and containing syntax highlighting bugs around regexes to a single line.

A more complete solution might involve looking at the regex's surrounding context, as they are legal in surprisingly few places in the grammar: https://docs.puppetlabs.com/puppet/latest/reference/lang_datatypes.html#regular-expressions

**Comment by p8952** [comment] 2015-04-17 13:38
For anyone else seeing this issue, one "solution" I have found it to write expressions like so:

`$x = $y / $z #/`

The trailing `#/` tricks vim into thinking the regex has been closed and allows everything under this expression to be highlighted correctly.

**Comment by lamawithonel** [comment] 2015-09-18 17:36
I thought I had a fix for this, but on second look, it introduces new bugs.  The problem is, a lot of the lexer tokens here don't match those used in the Puppet lexer.  That underlying problem will need to be fixed first, I think.

**Comment by GerbenWelter** [comment] 2017-08-07 12:08
A simple fix for me is to change the start parameter to check if it's preceded by another "/" and one or more other characters.

Change:

`syn region  puppetRegex            start="/" skip="\\/" end="/" contains=puppetRegexParen,puppetRegexBrace,puppetRegexOrpuppetRegexBrack,puppetRegexComment`

to:

`syn region  puppetRegex            start="\(?<!/.*\)/" skip="\\/" end="/" contains=puppetRegexParen,puppetRegexBrace,puppetRegexOrpuppetRegexBrack,puppetRegexComment`

This causes a line with a division not to be matched as a line starting a regex.

**Closed** 2019-04-23 00:03 UTC
