### ISSUE TITLE
vim freezes writing a text

### ISSUE THREAD

**Issue by amateo** [rodjek/vim-puppet#32] opened 2014-02-18 17:15 UTC
This is my manifest:

``` puppet
class users::telematica::ssh_user_keys (
  $keys = {},
) {
  create_resources(ssh_authorized_keys, XXX)
}
```

In the XXX text, whenever I try to replace it with ''${users::telematica::ssh_user_keys::keys}'' (this exact replace, I know it is wrong, because I don't have to surround the variable with {}, but the problem is when I use the {}) vim freezes and hangs and I have to open a terminal and kill it.

While it is freezed, a strace only shows lines like:

```
select(1, [0], NULL, [0], {0, 0})       = 0 (Timeout)
select(1, [0], NULL, [0], {0, 0})       = 0 (Timeout)
select(1, [0], NULL, [0], {0, 0})       = 0 (Timeout)
```

I have tried various ways to write the variable (writing it manually hangs around ''ssh_user_keys'' but I have tried to write it with a copy&paste).

If I remove vim-puppet plugin (I have it installed with pathogen and download it from github), then everything works fine. I have tested it with just vim-puppet plugin (removing other plugins I'm using) and with .vimrc only executing pathogen.

Any idea?

**Comment by evidex** [comment] 2015-08-06 09:34
Having a similar issue whenever I make an edit that would update the highlighting of a piece of text, such as removing `}` from the following:

`"${::hostname}_check_home_drive"`

This causes vim CPU usage to hit 100% (on a powerful machine). Issue cannot be replicated with vim-puppet removed. Issue is being seen on the latest version of vim-puppet:

`d881b93dc4a8ed1374ad44439aeeb47808a6b91a`

**Comment by evidex** [comment] 2015-08-06 11:53
Issue seems to be caused by Line 45 in `syntax/puppet.vim`

`syn match   puppetVariable           "$\(\(\(::\)\?\w\+\)\+\|{\(\(::\)\?\w\+\)\+}\)"`

**Comment by lelutin** [comment] 2016-12-14 10:14
fwiw I'm currently unable to reproduce with vim 8.0 (debian sid) and current master. when I remove the ending

the in puppet.vim line for "puppetVariable" (currently line 43) seems to still have the same regexp as mentioned by @evidex

**Comment by jkomara** [comment] 2016-12-17 05:08
Just pulled the latest today and started experiencing this. I am on vim 7.4 on osx. Commenting out the line @evidex suggested appears to work.

**Comment by lelutin** [comment] 2024-09-08 14:04
it's been quite a long time since this issue was opened. in #57 two ppl tried to reproduce on recent vim/nvim and couldn't.

So I'll assume that the problem might have been fixed by some patch on vim or neovim

If folks are still experiencing this issue after all this time, then don't hesitate to reopen and send us as much detail as you can on the version of vim/nvim and the commit of this module checked out. It might also be necessary to run a binary search on the editor version to see if the problem appeard and / disappeared at some point upstream

**Closed by lelutin** 2024-09-08 14:04 UTC
