### ISSUE TITLE
Remove closing brace hangs Vim

### ISSUE THREAD

**Issue by jorhett** [rodjek/vim-puppet#39] opened 2014-07-14 06:51 UTC
If you have a variable like this:

${variable} = "blah"

..and you decide to remove the brackets, if you remove the closing bracket first Vim will hang. Killing off Vim and then trying to edit the file produces another hang. You must disable the vim-puppet bundle or rename the file to something without the .pp suffix before you can use Vim to edit the file.

**Comment by evidex** [comment] 2015-08-06 09:35
+1. Replicates Issue #32

**Comment by linuxmail** [comment] 2017-05-13 10:34
Same for me.

**Comment by maage** [comment] 2021-01-21 12:00
I tried to replicate this with current tree and was not able to do it. Maybe it is fixed.

Fedora 33; vim-common-8.2.2146-2.fc33.x86_64

**Comment by lelutin** [comment] 2021-01-24 01:46
same, I'm on debian sid using vim 8.2.2367-1 and I can't replicate.

but among the two issues, there's been a good handful of ppl reporting they were experiencing the problem.

In both this report and #32, ppl experiencing the issue didn't give a lot of information about the vim versions and possible other plugins, so it's really hard to know what is affected by this. The only version noted is in the other report and it would be vim 7.4

I can try and replicate with vim 7.4, which means I'll have to spin up a debian jessie VM (e.g. currently oldoldstable).

if ppl are still experiencing this problem, it would help a lot to know which version of vim is affected, and if it's not too much trouble it would also help to test vim with only vim-puppet loaded so we can confirm it's not an interaction with something else that jams up vim.

**Comment by lelutin** [comment] 2021-01-24 02:11
so  I just tried in a vanilla jessie VM, installed vim-nox 2:7.4.488-7+deb8u4 and git, then setup vim this way:

~~~
cat ~/.vimrc <<EOF
syn on
filetype plugin indent on
EOF
git clone https://github.com/rodjek/vim-puppet.git .vim
~~~

and I tried reproducing the problem but it did not show. maybe the big rework of the syntax file that happened a while back removed the issue?

since the regexp for puppetVariable is now different, I've tried changing it back to `"$\(\(\(::\)\?\w\+\)\+\|{\(\(::\)\?\w\+\)\+}\)"` that was mentioned in #32 and I still couldn't reproduce.

**Comment by lelutin** [comment] 2021-01-24 02:20
I also checked out commit `d881b93dc4a8ed1374ad44439aeeb47808a6b91a` of the vim-puppet plugin since it was mentioned in #32 as showing the issue (with the same debian jessie setup as mentioned in my last comment), but the problem is not showing up.

I guess we'll need to have more information from ppl experiencing this. e.g.

 * vim version
 * vimrc
 * commit of this plugin used.

try to make your vimrc as small as possible and to load only vim-puppet. this way we can have a description of a way to reproduce and it'll also help to close in on potential options that cause the problem when enabled.

**Comment by lelutin** [comment] 2021-01-24 02:23
oh .. and also those details would help too:

* os
* distro (if linux or bsd)
* release name and/or version

**Comment by lelutin** [comment] 2024-09-08 14:00
Duplicate of #32

**Closed by lelutin** 2024-09-08 14:00 UTC
