### ISSUE TITLE
wrong indentation

### ISSUE THREAD

**Issue by ghost** [rodjek/vim-puppet#77] opened 2017-07-25 09:09 UTC
Hi,

the vim plugin doesn't seem to get the right indentation.

I have a class

```
#
class qmonitoring::unattended_upgrades {
  include apt
  # updates
  class { '::unattended_upgrades':
    auto => {
              'clean'       => 1,
              'reboot'      => true,
              'reboot_time' => '01:00',
              'remove'      => true,
    },
  }
}
```
and the plugin tries to move the auto attribute with the others to the right. Additionally it seems to use tabs instead of two character soft tabs (spaces).

I had to disable it.

**Comment by rodjek** [comment] 2017-07-25 11:08
@noobcontrol can you tell me more about your vim setup (version, settings, etc)? When I reindent that text (copy & pasted verbatim into a new file, reindented with `gg=G` from normal mode), I get a correctly 2 space indented file (maybe something else in your config is setting `noexpandtab`?).

**Comment by noobcontrol** [comment] 2017-07-25 11:17
It's Debian 9 with small adjustments. No local .vimrc configuration. I installed the vim-puppet from the package manger

I have attached my /etc/vim/vimrc for clarification.

```
" All system-wide defaults are set in $VIMRUNTIME/debian.vim and sourced by
" the call to :runtime you can find below.  If you wish to change any of those
" settings, you should do it in this file (/etc/vim/vimrc), since debian.vim
" will be overwritten everytime an upgrade of the vim packages is performed.
" It is recommended to make changes after sourcing debian.vim since it alters
" the value of the 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
syntax on
colorscheme koehler
"let g:puppet_align_hashes = 0
" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif
"endif

" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
"if has("autocmd")
"  filetype plugin indent on
"endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
"set showcmd		" Show (partial) command in status line.
"set showmatch		" Show matching brackets.
"set ignorecase		" Do case insensitive matching
"set smartcase		" Do smart case matching
"set incsearch		" Incremental search
"set autowrite		" Automatically save before commands like :next and :make
"set hidden		" Hide buffers when they are abandoned
"set mouse=a		" Enable mouse usage (all modes)

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
```

**Comment by rodjek** [comment] 2017-07-26 10:37
Sorry, I can't see a vim-puppet package for Debian 9 in the official repositories. Can you send me some more details about the package?

**Comment by lelutin** [comment] 2018-11-10 04:08
I've tried to reproduce this case and it does not produce the error described in the original description.

also, the vim-puppet package in debian is indeed not this plugin: it's the one that used to be maintained by puppetlabs (but it's been abandoned some years ago).

So: I'd recommend closing this issue

**Comment by lelutin** [comment] 2019-09-16 08:07
judging from the last line of your last comment, `Homepage: http://projects.puppetlabs.com/projects/puppet` suggests that indeed this was the previously available debian package which contained the vim plugin that was maintained by puppetlabs.

I'll close this issue since it doesn't seem to be affecting this code.

cheers!

**Closed by lelutin** 2019-09-16 08:07 UTC
