### ISSUE TITLE
Incorrect indentation

### ISSUE THREAD

**Issue by lpar** [rodjek/vim-puppet#67] opened 2017-01-10 20:37 UTC
I'm getting incorrect indentation, and can't work out why.

If I start with the following code:

```
    file { '/etc/default/stunnel':
      ensure  => 'file',
      content => "ENABLED=1\n",
      group   => '0',
      mode    => '0600',
      owner   => '0',
    }
```

If I move to the first line and type `=}` to reformat, I get:

```
    file { '/etc/default/stunnel':
      ensure  => 'file',
              content => "ENABLED=1\n",
              group   => '0',
              mode    => '0600',
              owner   => '0',
    }
```

My settings:

```
  backup              ignorecase          scrolloff=2         softtabstop=2           
  breakindent         iskeyword=@         shada='20,"50       syntax=puppet           
  columns=86        nojoinspaces          shiftround          tabstop=2               
  expandtab           linebreak           shiftwidth=2        undofile                
  filetype=puppet     lines=45            showbreak=└         undolevels=100          
  helplang=en         modelines=0         showcmd             undoreload=100          
  hidden              ruler               showmatch           viminfo='20,"50         
  history=50          scroll=21           smartcase           window=44                                                             
  complete=i,t,.,b,w,k,.                                                                                                                   
  fileencoding=utf-8                                                                  
  formatoptions=tcql                                                                                                                           
```

**Comment by rodjek** [comment] 2017-07-14 05:26
@lpar what's the sha of your vim-puppet checkout?

**Comment by lpar** [comment] 2017-07-14 21:28
commit cb1863af2ba4de9fb1c1d952d82692502348fb92
Merge: 2d8cd92 5669969
Author: Tim Sharpe <tim@sharpe.id.au>
Date:   Sun Jul 2 21:26:39 2017 +1000

    Merge pull request #76 from thompsa/master
    
    Use non-greedy regex matching when working out the indent.

NVIM 0.1.7, from Fedora 25 repos.

**Comment by lpar** [comment] 2017-07-14 21:33
OK, this is weird: If I copy the file somewhere else, I can open both copies in nvim at the same time in split window buffers, perform the reindent on the same block in each window pane, and it works for one of them and not the other.

**Comment by lelutin** [comment] 2018-11-10 04:12
Hi! for info, I've tried reproducing this with vim 8.1 on current master by copying the example in a "blah.pp" file and then asking vim to indent the block with the `=}` command and it didn't reproduce the error.

@lpar is it possible that there was some unprintable char either at the beginning or the end of the line that could have caused the weird behaviour?

**Comment by lpar** [comment] 2018-11-12 14:58
Just reproduced it with both vim 8.1 and neovim 0.3.1. There are no control codes. It happens even if the entire file is just this:

```
class domino {

  service {'stunnel':
    ensure  => 'running',
            enable  => true,
            require => [
              Package['stunnel'],
              File['stunnel-ldaps.conf'],
              File['/etc/default/stunnel'],
              File['/etc/init.d/stunnel']],
  }

}
```

However, it only seems to happen if the file is called `init.pp`. If I take the same file and copy it to `test.pp` and edit that instead, the problem doesn't happen in the copy.

**Comment by lelutin** [comment] 2021-01-30 21:55
sorry, I was eaten by a grue somewhere around two years ago. my respawn just happened during the holidays so now I'm back :)

I've tried to reproduce this again today and I'm unable to get the same results as you.

To make sure that there weren't any plugins interfering on my side, I started vim with the init script used for the tests. e.g.:

~~~
vim -u test/init.vim init.pp
~~~

Then I pasted the content of the first block quote in your first message, went on the first line and type `=}` and I got the following which doesn't match your issue (e.g. the leading spaces get removed but the lines stay indented correctly:

~~~
file { '/etc/default/stunnel':
  ensure  => 'file',
  content => "ENABLED=1\n",
  group   => '0',
  mode    => '0600',
  owner   => '0',
}
~~~

after deleting all lines in the buffer, I also tried to paste in the content of the block quote from your latest message, and went on the line that starts with `service`, typed `=}` to get the lines till the first empty line formatted and I get the following:

~~~
class domino {

  service {'stunnel':
    ensure  => 'running',
    enable  => true,
    require => [
      Package['stunnel'],
      File['stunnel-ldaps.conf'],
      File['/etc/default/stunnel'],
      File['/etc/init.d/stunnel']],
  }

}
~~~

Could you try testing this again by starting vim or nvim with the same startup script? This way we eliminate other plugins or settings that could have a side-effect.

If it's still happening with the `init.vim` script as the vimrc, then I guess the best way to transfer to me how you're testing this would be to write a test file. This way we have a mechanized way of producing the bug.

On the contrary, if it's not happening anymore then we also have a clue! in that case you can start adding some things from your vimrc until the problem reoccurs and that'll tell you what's causing it.

**Comment by lelutin** [comment] 2024-09-08 13:42
no news for the last three years. I tried again to reproduce by checking out commit cb1863af2ba4de9fb1c1d952d82692502348fb92 and with both neovim 0.9.5 and vim 9.1, in a file named `init.pp`, the indentation gets fixed correctly after I remove some leading spaces, go to the line starting with `service` and hit `=}`

I will go ahead and close this since there weren't any other confirmations of the issues after all that time. Don't hesitate to reopen if you're still having issues with this. If that's the case, first try to update the vim-puppet module to the latest commit and restart your editor. If after that you're still seeing this happening, tell us which version of of vim or neovim you're currently using

Cheers!

**Closed by lelutin** 2024-09-08 13:42 UTC
